### ISSUE TITLE
Instability of fitexp

### ISSUE THREAD

**Issue by PierreBarrat** [m3g/EasyFit.jl#14]
Hi,
Thank you for this very nice package! 
I noticed that the exponential fit is sometimes unstable and converges to nonsense values (screenshots below).

I did not investigate further, but if needed I'd be happy to. 
Best,
Pierre  

![Capture du 2023-09-12 11-37-08](https://github.com/m3g/EasyFit.jl/assets/14330776/3f426b43-cf70-44f8-a1b6-4e1653430aef)
![Capture du 2023-09-12 11-34-34](https://github.com/m3g/EasyFit.jl/assets/14330776/26b07770-9779-4120-844b-536ae3590144)

**Comment by lmiq** [comment]
Yes, exponential fits are many times unstable. That's why we run the fit multiple times and return the best one. The number of trials can be set using
```
fitexp(x ,y, options=Options(maxtrials=500))
```

(The default is 100)

Increasing the number of trials improves the chances of the best fit to be found.

Despite that I don't know anything that can be done to provide a much more robust fitting, at least without using another algorithm which I would need to investigate.

**Comment by lmiq** [comment]
Nice. Increasing `nbest` provides a better guarantee to return the global minimum.
